# fly.toml app configuration file generated for tipicorss on 2023-08-24T17:53:55+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tipicorss"
primary_region = "sea"

[build]

[http_service]
  internal_port = 8080
  force_https = true
